name: Update Stream

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install yt-dlp
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Create cookies.txt
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Run script
        run: python update.py

      - name: Commit updated playlist
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add live.m3u
          git commit -m "update stream" || echo "no changes"
          git push
